### ISSUE TITLE
[feat] sfpegExcelLoaderCmp - Possibility to download import results

### ISSUE THREAD

**Issue by priyancajogoo** [pegros/PEG_EXCEL#1]
**Is your feature request related to a problem? Please describe.**
Regarding the import results are shown in an iteration using only the key.
However for bulk imports the way the failures and success are shown is not convenient/ readable for end users.

**Describe the solution you'd like**
The possibility to download the failures and success in a CSV/Excel file with the same columns as the import file + the Id of the success and errors of the failures.

**Describe alternatives you've considered**
Having the excel import file headers and import results exposed as a property so it can be handled and exported by a parent component.

**Additional context**
![Import with Id and without Id and Name](https://user-images.githubusercontent.com/122534448/214506546-d92f0add-d3cc-4fb9-b305-6518966cdb58.png)

**Comment by pegros** [comment]
Simplest solution would be to export results as CSV, leveraging existing feature on **_sfpegListCmp_** (see **_PEG_LIST_** repo).
I shall give it a try rapidly. @priyancajogoo

**Comment by priyancajogoo** [comment]
Hello @pegros , will it be possible to export the result in the same format as the import file which will be an excel file?
For large imports, there is also a delay between clicking the button and displaying the results. Will be possible to disable the import button or display a spinner after the import button is clicked to avoid multiple clicks?

Thank you.

**Comment by pegros** [comment]
@priyancajogoo  I implemented a first version of the Summary export and tried to add a spinner for the initial upload. This is still work in progress but it should already help you.

**Comment by pegros** [comment]
FYI @jstukas

**Comment by priyancajogoo** [comment]
Hello @pegros, Will it be possible to make the component accessible in flow please?
Thank you

**Comment by pegros** [comment]
@priyancajogoo  I shall give it a try

**Comment by pegros** [comment]
@priyancajogoo  I just added Flow Builder support (see commit [c4da1c4](https://github.com/pegros/PEG_EXCEL/commit/c4da1c4edea18dff34bf2c8ace1ff042556d1dde))
FYI @jstukas

**Comment by priyancajogoo** [comment]
Hello @pegros , could you give us an update on the status of the export functionality please?

**Comment by pegros** [comment]
Have you tried the latest version ? Is it not enough ?

**Comment by priyancajogoo** [comment]
Hello @pegros, Yes we have tried the latest version where the errors are exported in another tab. However it would be more helpful for users to receive the error on in the same sheet as the input with the error column in the last position (same as data loader/salesforce inspector's result format).
Hence, users can simply correct the lines needed without having to do a find/vlookup.

**Comment by pegros** [comment]
@priyancajogoo  Final update done. The summary export provides details per original imported line.
see [94a4767](https://github.com/pegros/PEG_EXCEL/commit/94a4767a2ecadde2797185d06a6412aa1ed85a8b)

FYI @jstukas
